// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dict.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PbDict {

  /// <summary>Holder for reflection information generated from dict.proto</summary>
  public static partial class DictReflection {

    #region Descriptor
    /// <summary>File descriptor for dict.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DictReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpkaWN0LnByb3RvEgdwYl9kaWN0KuQhCgVFRGljdBIPCgthY3Rpb25fTk9O",
            "RRAAEhcKE2FjdGlvbl9DMlNfU29ydEl0ZW0QAxIXChNhY3Rpb25fQzJTX1Nl",
            "bGxJdGVtEAQSFwoTYWN0aW9uX1MyQ19TZWxsSXRlbRAFEhYKEmFjdGlvbl9D",
            "MlNfVXNlSXRlbRAGEhYKEmFjdGlvbl9TMkNfVXNlSXRlbRAHEhgKFGFjdGlv",
            "bl9DMlNfQnJlYWtJdGVtEAgSGAoUYWN0aW9uX1MyQ19CcmVha0l0ZW0QCRIZ",
            "ChVhY3Rpb25fQzJTX0VxdWlwTW91bnQQEBIZChVhY3Rpb25fUzJDX0VxdWlw",
            "TW91bnQQERIbChdhY3Rpb25fQzJTX1VuRXF1aXBNb3VudBASEhsKF2FjdGlv",
            "bl9TMkNfVW5FcXVpcE1vdW50EBMSGAoUYWN0aW9uX1MyQ19BQVNOb3RpY2UQ",
            "FBIXChNhY3Rpb25fQzJTX0J1eUdvb2RzEBoSFwoTYWN0aW9uX1MyQ19CdXlH",
            "b29kcxAbEhgKFHBiX2JhZ19DMlNfRXh0ZW5kQmFnECISGAoUcGJfYmFnX1My",
            "Q19FeHRlbmRCYWcQIxIVChFhY3Rpb25fQzJTX1JlY2FzdBAmEhUKEWFjdGlv",
            "bl9TMkNfUmVjYXN0ECcSGAoUYWN0aW9uX0MyU19Db21wb3NpdGUQLBIYChRh",
            "Y3Rpb25fUzJDX0NvbXBvc2l0ZRAtEhkKFWFjdGlvbl9DMlNfU3R1ZHlQYXBl",
            "chAuEhkKFWFjdGlvbl9TMkNfU3R1ZHlQYXBlchAvEh0KGWFjdGlvbl9DMlNf",
            "Q2hhbmdlVXNlck5hbWUQNBIdChlhY3Rpb25fUzJDX0NoYW5nZVVzZXJOYW1l",
            "EDUSGQoVYWN0aW9uX1MyQ19Vc2VyR2V0RXhwEDYSGQoVYWN0aW9uX1MyQ19P",
            "cGVyYXRpb25zEDcSIAocYWN0aW9uX0MyU19RdWVyeVJlY2FzdE1hc3RlchA4",
            "EiAKHGFjdGlvbl9TMkNfUXVlcnlSZWNhc3RNYXN0ZXIQORIXChNhY3Rpb25f",
            "UzJDX1NvcnRJdGVtEEsSIgoeYWN0aW9uX0MyU19SZWNlaXZlRGFpbHlCYW5x",
            "dWV0EEwSIgoeYWN0aW9uX1MyQ19SZWNlaXZlRGFpbHlCYW5xdWV0EE0SGwoW",
            "cGJfbWFpbF9DMlNfUXVlcnlNYWlscxC6ARIbChZwYl9tYWlsX1MyQ19RdWVy",
            "eU1haWxzELsBEiAKG3BiX21haWxfQzJTX1F1ZXJ5TWFpbERldGFpbBC8ARIg",
            "ChtwYl9tYWlsX1MyQ19RdWVyeU1haWxEZXRhaWwQvQESGwoWcGJfbWFpbF9D",
            "MlNfRGVsZXRlTWFpbBC+ARIbChZwYl9tYWlsX1MyQ19EZWxldGVNYWlsEL8B",
            "Eh4KGXBiX21haWxfQzJTX1Rha2VNYWlsSXRlbXMQwAESHgoZcGJfbWFpbF9T",
            "MkNfVGFrZU1haWxJdGVtcxDBARIbChZwYl9tYWlsX1MyQ19NYWlsTm90aWNl",
            "EMIBEhEKDHBhY2tldF9FcnJvchDpARIWChFwYWNrZXRfUGFja2V0SGVhZBDq",
            "ARIUCg9zaGFyZWRfTG9jYXRpb24Q6wESEwoOc2hhcmVkX1ZlcnNpb24Q7AES",
            "EAoLc2hhcmVkX0l0ZW0Q7QESFwoSc2hhcmVkX1dlYXBvbkFmZml4EO4BEhIK",
            "DXNoYXJlZF9XZWFwb24Q7wESGgoVc2hhcmVkX1BhcGVyQ29tcG9zaXRlEPAB",
            "EhAKC3NoYXJlZF9NYXNrEPEBEhUKEHNoYXJlZF9Gb3JtYXRpb24Q8gESEgoN",
            "c2hhcmVkX1BsYXllchDzARIRCgxzaGFyZWRfUXVlc3QQ9QESFAoPc2hhcmVk",
            "X1Byb2dyZXNzEPYBEg8KCnNoYXJlZF9OUEMQ9wESEgoNc2hhcmVkX0ZyaWVu",
            "ZBD4ARIVChBzaGFyZWRfQmxhY2tsaXN0EPkBEhEKDHNoYXJlZF9Nb3VudBD6",
            "ARISCg1zaGFyZWRfVGFsZW50EPsBEhAKC3NoYXJlZF9SYWNlEPwBEhAKC3No",
            "YXJlZF9GYW1lEP0BEhMKDnNoYXJlZF9NYXBCdWZmEP4BEhQKD3NoYXJlZF9U",
            "dXRvcmlhbBD/ARIXChJzaGFyZWRfQWNoaWV2ZW1lbnQQgAISFQoQc2hhcmVk",
            "X1N0YXRpc3RpYxCBAhIQCgtzaGFyZWRfUnVuZRCCAhIUCg9zaGFyZWRfUnVu",
            "ZVBhZ2UQgwISFQoQc2hhcmVkX0Zvcm11bGFJZBCEAhIUCg9zaGFyZWRfSXRl",
            "bUNlbGwQhQISDwoKc2hhcmVkX0JhZxCGAhIQCgtzaGFyZWRfU2lnbhCHAhIX",
            "ChJzaGFyZWRfVXNlclZlcnNpb24QiAISFAoPc2hhcmVkX1VzZXJEYXRhEIkC",
            "EhUKEHNoYXJlZF9PcGVyYXRpb24QigISEAoLc2hhcmVkX1BpbmcQiwISEAoL",
            "c2hhcmVkX1BvbmcQjAISGQoUc2hhcmVkX1NlcnZlck1lc3NhZ2UQjQISEAoL",
            "c2hhcmVkX0xvb3QQjgISEQoMc2hhcmVkX0dvb2RzEI8CEhYKEXNoYXJlZF9G",
            "YW1lRG9uYXRlEJACEhoKFWt2c3RvcmVfQzJTX1B1dEtWSXRlbRC/AhIaChVr",
            "dnN0b3JlX1MyQ19QdXRLVkl0ZW0QwAISGwoWcGJfcXVlcnlfQzJTX1F1ZXJ5",
            "VXNlchC8BRIbChZwYl9xdWVyeV9TMkNfUXVlcnlVc2VyEL0FEhwKF3BiX3F1",
            "ZXJ5X0MyU19RdWVyeUdvb2RzEL8FEhwKF3BiX3F1ZXJ5X1MyQ19RdWVyeUdv",
            "b2RzEMAFEiEKHHBiX3F1ZXJ5X0MyU19RdWVyeVNlcnZlclRpbWUQwQUSIQoc",
            "cGJfcXVlcnlfUzJDX1F1ZXJ5U2VydmVyVGltZRDCBRIiCh1wYl9xdWVyeV9D",
            "MlNfUXVlcnlCYXR0bGVTdGF0ZRDDBRIiCh1wYl9xdWVyeV9TMkNfUXVlcnlC",
            "YXR0bGVTdGF0ZRDEBRIgChtwYl9xdWVyeV9DMlNfUXVlcnlPdGhlclVzZXIQ",
            "xQUSIAobcGJfcXVlcnlfUzJDX1F1ZXJ5T3RoZXJVc2VyEMYFEiYKIXBiX3F1",
            "ZXJ5X1MyQ19RdWVyeU90aGVyVXNlck5vdGlmeRDHBRIdChhwYl9xdWVyeV9D",
            "MlNfUXVlcnlNeVByb3AQyAUSHQoYcGJfcXVlcnlfUzJDX1F1ZXJ5TXlQcm9w",
            "EMkFEhwKF3BiX3F1ZXJ5X0MyU19RdWVyeVNob3BzEMoFEhwKF3BiX3F1ZXJ5",
            "X1MyQ19RdWVyeVNob3BzEMsFEiEKHHBiX3F1ZXJ5X0MyU19RdWVyeUxpbWl0",
            "R29vZHMQzAUSIQoccGJfcXVlcnlfUzJDX1F1ZXJ5TGltaXRHb29kcxDNBRIb",
            "ChZwYl9xdWVyeV9DMlNfU2VjUmVwb3J0EM4FEhsKFnBiX3F1ZXJ5X1MyQ19T",
            "ZWNSZXBvcnQQzwUSGgoVcGJfc2VydmVyX1MyQ19LaWNrb3V0EM4IEh0KGHBi",
            "X3NlcnZlcl9TMkNfU2VydmVySW5mbxDPCBIdChhwYl9zZXJ2ZXJfUzJDX05v",
            "dGljZUxpc3QQ0AgSHQoYcGJfc2VydmVyX0MyU19Ob3RpY2VMaXN0ENEIEh8K",
            "GnBiX3NlcnZlcl9DMlNfV29ybGRFeHBMb2NrENIIEh8KGnBiX3NlcnZlcl9T",
            "MkNfV29ybGRFeHBMb2NrENMIEiIKHWFjdGlvbl9DMlNfRG9uYXRlR2xvYmFs",
            "RG9uYXRlEIkJEiIKHWFjdGlvbl9TMkNfRG9uYXRlR2xvYmFsRG9uYXRlEIoJ",
            "EiEKHGFjdGlvbl9DMlNfUXVlcnlHbG9iYWxEb25hdGUQiwkSIQocYWN0aW9u",
            "X1MyQ19RdWVyeUdsb2JhbERvbmF0ZRCMCRIiCh1hY3Rpb25fQzJTX01vdmVF",
            "cXVpcEV4dHJhUHJvcBCNCRIiCh1hY3Rpb25fUzJDX01vdmVFcXVpcEV4dHJh",
            "UHJvcBCOCRIhChxhY3Rpb25fQzJTX0FkZEVxdWlwRXh0cmFQcm9wEI8JEiEK",
            "HGFjdGlvbl9TMkNfQWRkRXF1aXBFeHRyYVByb3AQkAkSFgoRcGJfbG9naW5f",
            "QzJTX0F1dGgQzwkSFgoRcGJfbG9naW5fUzJDX0F1dGgQ0AkSGwoWcGJfbG9n",
            "aW5fQzJTX0VudGVyR2FtZRDRCRIbChZwYl9sb2dpbl9TMkNfRW50ZXJHYW1l",
            "ENIJEh8KGnBiX2xvZ2luX1MyQ19FbnRyYW5jZVF1ZXVlENMJEhwKF3BiX2xv",
            "Z2luX0MyU19DcmVhdGVSb2xlENQJEhwKF3BiX2xvZ2luX1MyQ19DcmVhdGVS",
            "b2xlENUJEhsKFnBiX2xvZ2luX0MyU19IZWFydEJlYXQQ4gkSGwoWcGJfbG9n",
            "aW5fUzJDX0hlYXJ0QmVhdBDjCRIaChVwYl9jaGF0X0MyU19JbnRlckNoYXQQ",
            "pBISGgoVcGJfY2hhdF9TMkNfSW50ZXJDaGF0EKUSEhwKF3BiX2NoYXRfUzJD",
            "X011bHRpcGxlTXNnEKYSEh0KGHBiX2NoYXRfUzJDX0NsZWFyTWVzc2FnZRCn",
            "EhIvCipwYl9tb25pdG9yQWN0aXZpdHlfUzJDX09wZXJhdGVBY3Rpdml0eUlu",
            "Zm8QqRQSMAorcGJfbW9uaXRvckFjdGl2aXR5X0MyU19HZXRPcGVyYXRlQWN0",
            "aXZpdGllcxCqFBIwCitwYl9tb25pdG9yQWN0aXZpdHlfUzJDX0dldE9wZXJh",
            "dGVBY3Rpdml0aWVzEKsUEjAKK3BiX21vbml0b3JBY3Rpdml0eV9DMlNfR2V0",
            "T3BlcmF0ZVRhc2tSZXdhcmQQrBQSMAorcGJfbW9uaXRvckFjdGl2aXR5X1My",
            "Q19HZXRPcGVyYXRlVGFza1Jld2FyZBCtFBIfChpwYl9yYW5rX0MyU19UYXJn",
            "ZXRSYW5rTGlzdBDAJRIfChpwYl9yYW5rX1MyQ19UYXJnZXRSYW5rTGlzdBDB",
            "JRIjCh5wYl9zdGF0aXN0aWNfQzJTX1N0YXRpc3RpY0RhdGEQ3iUSIwoecGJf",
            "c3RhdGlzdGljX1MyQ19TdGF0aXN0aWNEYXRhEN8lEh0KGHBiX21hdGNoX0My",
            "U19CYXR0bGVNYXRjaBD7LhIdChhwYl9tYXRjaF9TMkNfQmF0dGxlTWF0Y2gQ",
            "/C4SIwoecGJfbWF0Y2hfQzJTX0JhdHRsZUNhbmNlbE1hdGNoEIUvEiMKHnBi",
            "X21hdGNoX1MyQ19CYXR0bGVDYW5jZWxNYXRjaBCGLxIkCh9wYl9tYXRjaF9T",
            "MkNfQmF0dGxlTWF0Y2hUaW1lb3V0EIcvEh8KGXBiX2JhdHRsZV9TMkNfU3Rh",
            "cnRCYXR0bGUQ2oYDEh8KGXBiX2JhdHRsZV9DMlNfRW50ZXJCYXR0bGUQ5YYD",
            "Eh8KGXBiX2JhdHRsZV9TMkNfRW50ZXJCYXR0bGUQ5oYDEiAKGnBiX2JhdHRs",
            "ZV9DMlNfQmF0dGxlQWN0aW9uEO+GAxIgChpwYl9iYXR0bGVfUzJDX0JhdHRs",
            "ZUFjdGlvbhDwhgMSJgogcGJfYmF0dGxlX1MyQ19VcGRhdGVCYXR0bGVBY3Rp",
            "b24Q8YYDEh0KF3BiX2JhdHRsZV9TMkNfQmF0dGxlRW5kEIKHAxIiChxwYl9i",
            "YXR0bGVfUzJDX0JhdHRsZUNhbmNlbGVkEIOHA0IMWgpwYi9wYl9kaWN0YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PbDict.EDict), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EDict {
    [pbr::OriginalName("action_NONE")] ActionNone = 0,
    [pbr::OriginalName("action_C2S_SortItem")] ActionC2SSortItem = 3,
    [pbr::OriginalName("action_C2S_SellItem")] ActionC2SSellItem = 4,
    [pbr::OriginalName("action_S2C_SellItem")] ActionS2CSellItem = 5,
    [pbr::OriginalName("action_C2S_UseItem")] ActionC2SUseItem = 6,
    [pbr::OriginalName("action_S2C_UseItem")] ActionS2CUseItem = 7,
    [pbr::OriginalName("action_C2S_BreakItem")] ActionC2SBreakItem = 8,
    [pbr::OriginalName("action_S2C_BreakItem")] ActionS2CBreakItem = 9,
    [pbr::OriginalName("action_C2S_EquipMount")] ActionC2SEquipMount = 16,
    [pbr::OriginalName("action_S2C_EquipMount")] ActionS2CEquipMount = 17,
    [pbr::OriginalName("action_C2S_UnEquipMount")] ActionC2SUnEquipMount = 18,
    [pbr::OriginalName("action_S2C_UnEquipMount")] ActionS2CUnEquipMount = 19,
    [pbr::OriginalName("action_S2C_AASNotice")] ActionS2CAasnotice = 20,
    [pbr::OriginalName("action_C2S_BuyGoods")] ActionC2SBuyGoods = 26,
    [pbr::OriginalName("action_S2C_BuyGoods")] ActionS2CBuyGoods = 27,
    [pbr::OriginalName("pb_bag_C2S_ExtendBag")] PbBagC2SExtendBag = 34,
    [pbr::OriginalName("pb_bag_S2C_ExtendBag")] PbBagS2CExtendBag = 35,
    [pbr::OriginalName("action_C2S_Recast")] ActionC2SRecast = 38,
    [pbr::OriginalName("action_S2C_Recast")] ActionS2CRecast = 39,
    [pbr::OriginalName("action_C2S_Composite")] ActionC2SComposite = 44,
    [pbr::OriginalName("action_S2C_Composite")] ActionS2CComposite = 45,
    [pbr::OriginalName("action_C2S_StudyPaper")] ActionC2SStudyPaper = 46,
    [pbr::OriginalName("action_S2C_StudyPaper")] ActionS2CStudyPaper = 47,
    [pbr::OriginalName("action_C2S_ChangeUserName")] ActionC2SChangeUserName = 52,
    [pbr::OriginalName("action_S2C_ChangeUserName")] ActionS2CChangeUserName = 53,
    [pbr::OriginalName("action_S2C_UserGetExp")] ActionS2CUserGetExp = 54,
    [pbr::OriginalName("action_S2C_Operations")] ActionS2COperations = 55,
    [pbr::OriginalName("action_C2S_QueryRecastMaster")] ActionC2SQueryRecastMaster = 56,
    [pbr::OriginalName("action_S2C_QueryRecastMaster")] ActionS2CQueryRecastMaster = 57,
    [pbr::OriginalName("action_S2C_SortItem")] ActionS2CSortItem = 75,
    [pbr::OriginalName("action_C2S_ReceiveDailyBanquet")] ActionC2SReceiveDailyBanquet = 76,
    [pbr::OriginalName("action_S2C_ReceiveDailyBanquet")] ActionS2CReceiveDailyBanquet = 77,
    [pbr::OriginalName("pb_mail_C2S_QueryMails")] PbMailC2SQueryMails = 186,
    [pbr::OriginalName("pb_mail_S2C_QueryMails")] PbMailS2CQueryMails = 187,
    [pbr::OriginalName("pb_mail_C2S_QueryMailDetail")] PbMailC2SQueryMailDetail = 188,
    [pbr::OriginalName("pb_mail_S2C_QueryMailDetail")] PbMailS2CQueryMailDetail = 189,
    [pbr::OriginalName("pb_mail_C2S_DeleteMail")] PbMailC2SDeleteMail = 190,
    [pbr::OriginalName("pb_mail_S2C_DeleteMail")] PbMailS2CDeleteMail = 191,
    [pbr::OriginalName("pb_mail_C2S_TakeMailItems")] PbMailC2STakeMailItems = 192,
    [pbr::OriginalName("pb_mail_S2C_TakeMailItems")] PbMailS2CTakeMailItems = 193,
    [pbr::OriginalName("pb_mail_S2C_MailNotice")] PbMailS2CMailNotice = 194,
    [pbr::OriginalName("packet_Error")] PacketError = 233,
    [pbr::OriginalName("packet_PacketHead")] PacketPacketHead = 234,
    [pbr::OriginalName("shared_Location")] SharedLocation = 235,
    [pbr::OriginalName("shared_Version")] SharedVersion = 236,
    [pbr::OriginalName("shared_Item")] SharedItem = 237,
    [pbr::OriginalName("shared_WeaponAffix")] SharedWeaponAffix = 238,
    [pbr::OriginalName("shared_Weapon")] SharedWeapon = 239,
    [pbr::OriginalName("shared_PaperComposite")] SharedPaperComposite = 240,
    [pbr::OriginalName("shared_Mask")] SharedMask = 241,
    [pbr::OriginalName("shared_Formation")] SharedFormation = 242,
    [pbr::OriginalName("shared_Player")] SharedPlayer = 243,
    [pbr::OriginalName("shared_Quest")] SharedQuest = 245,
    [pbr::OriginalName("shared_Progress")] SharedProgress = 246,
    [pbr::OriginalName("shared_NPC")] SharedNpc = 247,
    [pbr::OriginalName("shared_Friend")] SharedFriend = 248,
    [pbr::OriginalName("shared_Blacklist")] SharedBlacklist = 249,
    [pbr::OriginalName("shared_Mount")] SharedMount = 250,
    [pbr::OriginalName("shared_Talent")] SharedTalent = 251,
    [pbr::OriginalName("shared_Race")] SharedRace = 252,
    [pbr::OriginalName("shared_Fame")] SharedFame = 253,
    [pbr::OriginalName("shared_MapBuff")] SharedMapBuff = 254,
    [pbr::OriginalName("shared_Tutorial")] SharedTutorial = 255,
    [pbr::OriginalName("shared_Achievement")] SharedAchievement = 256,
    [pbr::OriginalName("shared_Statistic")] SharedStatistic = 257,
    [pbr::OriginalName("shared_Rune")] SharedRune = 258,
    [pbr::OriginalName("shared_RunePage")] SharedRunePage = 259,
    [pbr::OriginalName("shared_FormulaId")] SharedFormulaId = 260,
    [pbr::OriginalName("shared_ItemCell")] SharedItemCell = 261,
    [pbr::OriginalName("shared_Bag")] SharedBag = 262,
    [pbr::OriginalName("shared_Sign")] SharedSign = 263,
    [pbr::OriginalName("shared_UserVersion")] SharedUserVersion = 264,
    [pbr::OriginalName("shared_UserData")] SharedUserData = 265,
    [pbr::OriginalName("shared_Operation")] SharedOperation = 266,
    [pbr::OriginalName("shared_Ping")] SharedPing = 267,
    [pbr::OriginalName("shared_Pong")] SharedPong = 268,
    [pbr::OriginalName("shared_ServerMessage")] SharedServerMessage = 269,
    [pbr::OriginalName("shared_Loot")] SharedLoot = 270,
    [pbr::OriginalName("shared_Goods")] SharedGoods = 271,
    [pbr::OriginalName("shared_FameDonate")] SharedFameDonate = 272,
    [pbr::OriginalName("kvstore_C2S_PutKVItem")] KvstoreC2SPutKvitem = 319,
    [pbr::OriginalName("kvstore_S2C_PutKVItem")] KvstoreS2CPutKvitem = 320,
    [pbr::OriginalName("pb_query_C2S_QueryUser")] PbQueryC2SQueryUser = 700,
    [pbr::OriginalName("pb_query_S2C_QueryUser")] PbQueryS2CQueryUser = 701,
    [pbr::OriginalName("pb_query_C2S_QueryGoods")] PbQueryC2SQueryGoods = 703,
    [pbr::OriginalName("pb_query_S2C_QueryGoods")] PbQueryS2CQueryGoods = 704,
    [pbr::OriginalName("pb_query_C2S_QueryServerTime")] PbQueryC2SQueryServerTime = 705,
    [pbr::OriginalName("pb_query_S2C_QueryServerTime")] PbQueryS2CQueryServerTime = 706,
    [pbr::OriginalName("pb_query_C2S_QueryBattleState")] PbQueryC2SQueryBattleState = 707,
    [pbr::OriginalName("pb_query_S2C_QueryBattleState")] PbQueryS2CQueryBattleState = 708,
    [pbr::OriginalName("pb_query_C2S_QueryOtherUser")] PbQueryC2SQueryOtherUser = 709,
    [pbr::OriginalName("pb_query_S2C_QueryOtherUser")] PbQueryS2CQueryOtherUser = 710,
    [pbr::OriginalName("pb_query_S2C_QueryOtherUserNotify")] PbQueryS2CQueryOtherUserNotify = 711,
    [pbr::OriginalName("pb_query_C2S_QueryMyProp")] PbQueryC2SQueryMyProp = 712,
    [pbr::OriginalName("pb_query_S2C_QueryMyProp")] PbQueryS2CQueryMyProp = 713,
    [pbr::OriginalName("pb_query_C2S_QueryShops")] PbQueryC2SQueryShops = 714,
    [pbr::OriginalName("pb_query_S2C_QueryShops")] PbQueryS2CQueryShops = 715,
    [pbr::OriginalName("pb_query_C2S_QueryLimitGoods")] PbQueryC2SQueryLimitGoods = 716,
    [pbr::OriginalName("pb_query_S2C_QueryLimitGoods")] PbQueryS2CQueryLimitGoods = 717,
    [pbr::OriginalName("pb_query_C2S_SecReport")] PbQueryC2SSecReport = 718,
    [pbr::OriginalName("pb_query_S2C_SecReport")] PbQueryS2CSecReport = 719,
    [pbr::OriginalName("pb_server_S2C_Kickout")] PbServerS2CKickout = 1102,
    [pbr::OriginalName("pb_server_S2C_ServerInfo")] PbServerS2CServerInfo = 1103,
    [pbr::OriginalName("pb_server_S2C_NoticeList")] PbServerS2CNoticeList = 1104,
    [pbr::OriginalName("pb_server_C2S_NoticeList")] PbServerC2SNoticeList = 1105,
    [pbr::OriginalName("pb_server_C2S_WorldExpLock")] PbServerC2SWorldExpLock = 1106,
    [pbr::OriginalName("pb_server_S2C_WorldExpLock")] PbServerS2CWorldExpLock = 1107,
    [pbr::OriginalName("action_C2S_DonateGlobalDonate")] ActionC2SDonateGlobalDonate = 1161,
    [pbr::OriginalName("action_S2C_DonateGlobalDonate")] ActionS2CDonateGlobalDonate = 1162,
    [pbr::OriginalName("action_C2S_QueryGlobalDonate")] ActionC2SQueryGlobalDonate = 1163,
    [pbr::OriginalName("action_S2C_QueryGlobalDonate")] ActionS2CQueryGlobalDonate = 1164,
    [pbr::OriginalName("action_C2S_MoveEquipExtraProp")] ActionC2SMoveEquipExtraProp = 1165,
    [pbr::OriginalName("action_S2C_MoveEquipExtraProp")] ActionS2CMoveEquipExtraProp = 1166,
    [pbr::OriginalName("action_C2S_AddEquipExtraProp")] ActionC2SAddEquipExtraProp = 1167,
    [pbr::OriginalName("action_S2C_AddEquipExtraProp")] ActionS2CAddEquipExtraProp = 1168,
    [pbr::OriginalName("pb_login_C2S_Auth")] PbLoginC2SAuth = 1231,
    [pbr::OriginalName("pb_login_S2C_Auth")] PbLoginS2CAuth = 1232,
    [pbr::OriginalName("pb_login_C2S_EnterGame")] PbLoginC2SEnterGame = 1233,
    [pbr::OriginalName("pb_login_S2C_EnterGame")] PbLoginS2CEnterGame = 1234,
    [pbr::OriginalName("pb_login_S2C_EntranceQueue")] PbLoginS2CEntranceQueue = 1235,
    [pbr::OriginalName("pb_login_C2S_CreateRole")] PbLoginC2SCreateRole = 1236,
    [pbr::OriginalName("pb_login_S2C_CreateRole")] PbLoginS2CCreateRole = 1237,
    [pbr::OriginalName("pb_login_C2S_HeartBeat")] PbLoginC2SHeartBeat = 1250,
    [pbr::OriginalName("pb_login_S2C_HeartBeat")] PbLoginS2CHeartBeat = 1251,
    /// <summary>
    ///聊天
    /// </summary>
    [pbr::OriginalName("pb_chat_C2S_InterChat")] PbChatC2SInterChat = 2340,
    /// <summary>
    /// 服务器-客户端聊天消息
    /// </summary>
    [pbr::OriginalName("pb_chat_S2C_InterChat")] PbChatS2CInterChat = 2341,
    /// <summary>
    ///  服务器-客户端聊天消息 多条消息
    /// </summary>
    [pbr::OriginalName("pb_chat_S2C_MultipleMsg")] PbChatS2CMultipleMsg = 2342,
    /// <summary>
    ///服务器-客户端聊天消息 清除某玩家发送的消息
    /// </summary>
    [pbr::OriginalName("pb_chat_S2C_ClearMessage")] PbChatS2CClearMessage = 2343,
    /// <summary>
    ///服务器收到运营发送到活动后向客户端推消息
    /// </summary>
    [pbr::OriginalName("pb_monitorActivity_S2C_OperateActivityInfo")] PbMonitorActivityS2COperateActivityInfo = 2601,
    /// <summary>
    ///拉取运营活动消息
    /// </summary>
    [pbr::OriginalName("pb_monitorActivity_C2S_GetOperateActivities")] PbMonitorActivityC2SGetOperateActivities = 2602,
    /// <summary>
    ///下发运营活动消息
    /// </summary>
    [pbr::OriginalName("pb_monitorActivity_S2C_GetOperateActivities")] PbMonitorActivityS2CGetOperateActivities = 2603,
    /// <summary>
    ///领取运营活动奖励
    /// </summary>
    [pbr::OriginalName("pb_monitorActivity_C2S_GetOperateTaskReward")] PbMonitorActivityC2SGetOperateTaskReward = 2604,
    /// <summary>
    ///下发运营活动奖励
    /// </summary>
    [pbr::OriginalName("pb_monitorActivity_S2C_GetOperateTaskReward")] PbMonitorActivityS2CGetOperateTaskReward = 2605,
    /// <summary>
    /// 排行榜
    /// </summary>
    [pbr::OriginalName("pb_rank_C2S_TargetRankList")] PbRankC2STargetRankList = 4800,
    /// <summary>
    /// 请求指定id的排行榜信息
    /// </summary>
    [pbr::OriginalName("pb_rank_S2C_TargetRankList")] PbRankS2CTargetRankList = 4801,
    /// <summary>
    /// 统计数据
    /// </summary>
    [pbr::OriginalName("pb_statistic_C2S_StatisticData")] PbStatisticC2SStatisticData = 4830,
    /// <summary>
    /// 查询玩家累计统计信息
    /// </summary>
    [pbr::OriginalName("pb_statistic_S2C_StatisticData")] PbStatisticS2CStatisticData = 4831,
    /// <summary>
    ///匹配服
    /// </summary>
    [pbr::OriginalName("pb_match_C2S_BattleMatch")] PbMatchC2SBattleMatch = 6011,
    /// <summary>
    /// 玩家申请战斗匹配下发
    /// </summary>
    [pbr::OriginalName("pb_match_S2C_BattleMatch")] PbMatchS2CBattleMatch = 6012,
    /// <summary>
    /// 玩家申请取消战斗匹配
    /// </summary>
    [pbr::OriginalName("pb_match_C2S_BattleCancelMatch")] PbMatchC2SBattleCancelMatch = 6021,
    /// <summary>
    /// 玩家申请取消战斗匹配下发
    /// </summary>
    [pbr::OriginalName("pb_match_S2C_BattleCancelMatch")] PbMatchS2CBattleCancelMatch = 6022,
    /// <summary>
    ///战斗匹配超时
    /// </summary>
    [pbr::OriginalName("pb_match_S2C_BattleMatchTimeout")] PbMatchS2CBattleMatchTimeout = 6023,
    /// <summary>
    /// 战斗服相关cmd，都大于50000
    /// </summary>
    [pbr::OriginalName("pb_battle_S2C_StartBattle")] PbBattleS2CStartBattle = 50010,
    /// <summary>
    /// 玩家进入战斗
    /// </summary>
    [pbr::OriginalName("pb_battle_C2S_EnterBattle")] PbBattleC2SEnterBattle = 50021,
    /// <summary>
    /// 玩家进入战斗回复
    /// </summary>
    [pbr::OriginalName("pb_battle_S2C_EnterBattle")] PbBattleS2CEnterBattle = 50022,
    /// <summary>
    /// 玩家战斗中操作
    /// </summary>
    [pbr::OriginalName("pb_battle_C2S_BattleAction")] PbBattleC2SBattleAction = 50031,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("pb_battle_S2C_BattleAction")] PbBattleS2CBattleAction = 50032,
    /// <summary>
    /// 玩家战斗中操作下发
    /// </summary>
    [pbr::OriginalName("pb_battle_S2C_UpdateBattleAction")] PbBattleS2CUpdateBattleAction = 50033,
    /// <summary>
    /// 战斗结束下发
    /// </summary>
    [pbr::OriginalName("pb_battle_S2C_BattleEnd")] PbBattleS2CBattleEnd = 50050,
    /// <summary>
    /// 战斗取消下发
    /// </summary>
    [pbr::OriginalName("pb_battle_S2C_BattleCanceled")] PbBattleS2CBattleCanceled = 50051,
  }

  #endregion

}

#endregion Designer generated code
